"""add phone number to users table

Revision ID: 005a3ce14015
Revises: ae1f533a9187
Create Date: 2023-05-05 13:06:46.854585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005a3ce14015'
down_revision = 'ae1f533a9187'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
